# Generated by Django 3.2.7 on 2021-09-20 14:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_vote', to='restaurant.menu'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=2),
        ),
        migrations.CreateModel(
            name='RestaurantWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=2)),
                ('winning_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_winner', to='restaurant.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
