# Generated by Django 3.2.7 on 2021-09-20 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210921_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantwinner',
            name='winning_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
